# /home/siisi/e-commerce/docker-compose.prod.yml

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ecommerce_prod_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=prod

  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - gunicorn
      - ecommerce.wsgi:application
      - --bind
      - 0.0.0.0:8005
      - --log-level=debug
      - --access-logfile=/var/log/siisi/e-commerce/logs/e-commerce.log
      - --error-logfile=/var/log/siisi/e-commerce/logs/e-commerce.log
    environment:
      - ENVIRONMENT=prod
    volumes:
      - ./logs:/var/log/siisi/e-commerce/logs
      - ./media:/app/media
    depends_on:
      - db
    env_file:
      - .env.prod
    ports:
      - "8005:8005"


volumes:
  ecommerce_prod_data:
  static_volume:
  media_volume:
