# /home/siisi/e-commerce/docker-compose.dev.yml

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  ecommerce:
    build:
      context: .
    #command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8005 --log-level debug
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8005 --log-level debug --access-logfile /var/log/siisi/e-commerce/logs/e-commerce.log --error-logfile /var/log/siisi/e-commerce/logs/e-commerce.log
    volumes:
      - .:/app
      - ./logs:/var/log/siisi/e-commerce/logs
    ports:
      - "8006:8005"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}

volumes:
  postgres_data:
