# /home/siisi/e-commerce/docker-compose.dev.yml

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=secret_password

  ecommerce:
    build:
      context: .
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8005
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://django_user:secret_password@db:5432/django_db
      - DEBUG=1

volumes:
  postgres_data:
