# /home/siisi/e-commerce/docker-compose.dev.yml

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    environment:
      - ENVIRONMENT=dev

  ecommerce:
    build:
      context: .
    command:
      - gunicorn
      - ecommerce.wsgi:application
      - --bind
      - 0.0.0.0:8005
      - --log-level=debug
      - --access-logfile=/var/log/siisi/e-commerce/logs/e-commerce.log
      - --error-logfile=/var/log/siisi/e-commerce/logs/e-commerce.log
    volumes:
      - .:/app
      - ./logs:/var/log/siisi/e-commerce/logs
    ports:
      - "8006:8005"
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      - ENVIRONMENT=dev

volumes:
  postgres_data:
